# rutina.py — contingut estàtic del pla

FOAM = [
    {"zona": "TFL", "dosi": "60 s/costat",
     "on": "2 dits sota la cresta ilíaca, cara davantera-lateral del maluc. És un múscul petit, del mida d'un puny.",
     "com": "Estirat de costat, roller sota el maluc. Busca el punt sensible i ATURA'T. Pressió sostinguda 60s respirant. Si vols més, flexiona i estén el genoll lentament amb la pressió posada.",
     "per": "El TFL és qui tensa la banda IT. Alliberar-lo baixa la tensió de tota la banda sense tocar-la.",
     "yt": "TFL foam roller release"},
    {"zona": "Gluti mitjà", "dosi": "45 s/costat",
     "on": "Lateral del maluc, per sobre i darrere del trocànter (l'os que sobresurt).",
     "com": "Assegut sobre el roller o pilota, inclinat cap al costat que treballes. Roda lent, para als punts durs.",
     "per": "Gluti mitjà tens i inhibit = maluc inestable = més fricció al genoll.",
     "yt": "glute medius foam roller"},
    {"zona": "Vast lateral", "dosi": "45 s/costat",
     "on": "Cara EXTERNA de la cuixa, entre el maluc i el genoll. És múscul, no la banda.",
     "com": "Estirat de costat, roller sota la cuixa externa. Roda lent de maluc a genoll. Evita els últims 5 cm sobre el genoll.",
     "per": "Comparteix inserció amb la banda IT. Alliberar-lo baixa tensió al genoll extern.",
     "yt": "vastus lateralis foam roll"},
]

DINAMIC = [
    {"exercici": "90/90 hip switch", "dosi": "10 canvis/costat",
     "què": "Assegut amb una cama a 90° davant i l'altra a 90° al costat. Canvies de costat girant els malucs.",
     "com": "Assegut, cama davantera flexionada 90° davant teu, cama de darrere 90° al costat. Gira els dos genolls cap a l'altre costat sense fer servir les mans (o amb ajuda al principi). Tors recte.",
     "per": "El que més et falta. Rotació interna i externa de maluc — la bici t'ho tanca tot.",
     "yt": "90 90 hip switch mobility"},
    {"exercici": "Couch stretch dinàmic", "dosi": "8 pulsacions/costat",
     "què": "Genoll a terra, peu de darrere elevat contra una paret o banc.",
     "com": "Genoll al terra a la base d'una paret, tíbia vertical contra la paret. Cama davantera en angle recte. CONTREU EL GLUTI del costat estirat i amaga el cul (retroversió). Pulsa 8 cops endavant. Si arqueges la lumbar, has anat massa.",
     "per": "Flexor del maluc i recte femoral. El múscul que t'escurça la cadira i la bici.",
     "yt": "couch stretch technique"},
    {"exercici": "World's greatest stretch", "dosi": "5/costat",
     "què": "Estocada profunda + rotació del tors cap al sostre.",
     "com": "Estocada llarga, mà interior al terra al costat del peu davanter. Colze cap al terra 1s. Després gira el tors obrint el braç cap al sostre, mirada seguint la mà. Torna i canvia.",
     "per": "Fa cinc coses alhora: maluc, isquios, adductors, toràcica i espatlla.",
     "yt": "worlds greatest stretch"},
    {"exercici": "Rotació toràcica quadrupèdia", "dosi": "8/costat",
     "què": "A quatre grapes, gires el tors obrint el pit.",
     "com": "A quatre grapes, mà al clatell. Baixa el colze cap al braç contrari, després obre girant el pit cap al sostre. El moviment ve de les costelles, NO de la lumbar.",
     "per": "Toràcica. Sense això, el press militar i el front squat no surten sense arquejar la lumbar.",
     "yt": "thoracic rotation quadruped"},
    {"exercici": "Squat prying (goblet)", "dosi": "45 s",
     "què": "Aguantar la posició baixa de l'squat i moure't dins d'ella.",
     "com": "Manuella lleugera (8-12 kg) al pit. Baixa al fons de l'squat i QUEDA-T'HI. Empeny els genolls cap enfora amb els colzes. Balanceja't lateralment, endavant i enrere. Respira.",
     "per": "Obre turmell, adductors i maluc en la posició exacta on entrenaràs.",
     "yt": "goblet squat prying mobility"},
    {"exercici": "Balanceig de cama frontal i lateral", "dosi": "12/direcció/cama",
     "què": "Balancejar la cama endavant-enrere i lateralment, agafat a alguna cosa.",
     "com": "Agafat a una paret o barra. Balanceja endavant-enrere 12 cops, després lateral creuant davant del cos 12 cops. Progressiu: comença curt i ves ampliant. SENSE rebot forçat.",
     "per": "Prepara el maluc per al rang complet. Activa sense fatigar.",
     "yt": "leg swings warm up"},
]

MINIBANDS = [
    {"exercici": "Monster walk lateral (banda 5 kg)", "dosi": "2x15 passos/direcció",
     "què": "Caminar de costat amb la banda als turmells, en mitja sentadeta.",
     "com": "Banda als turmells, mitja sentadeta, peus paral·lels. Fes passos laterals mantenint tensió SEMPRE (els peus no es toquen mai). 15 passos a un costat, 15 tornant. Tors quiet.",
     "per": "Activa el gluti mitjà abans d'entrenar. Aquest és el teu exercici de prevenció BIT número 1.",
     "yt": "monster walk lateral band"},
    {"exercici": "Clamshell amb pausa 2s (banda 6 kg)", "dosi": "2x12/costat",
     "què": "Estirat de costat, obrir el genoll de dalt com una cloïssa.",
     "com": "De costat, genolls flexionats 90°, banda per sobre dels genolls. Peus junts SEMPRE. Obre el genoll de dalt, pausa 2s, tanca lent. El maluc NO ha de rodar enrere — si roda, has anat massa.",
     "per": "Rotadors externs del maluc. El que impedeix que el genoll caigui cap a dins a l'squat.",
     "yt": "clamshell exercise glute"},
    {"exercici": "Pont de gluti amb abducció", "dosi": "2x15",
     "què": "Pont de gluti + obrir genolls contra la banda a dalt.",
     "com": "Estirat de panxa amunt, genolls flexionats, banda sobre els genolls. Puja el maluc contraient gluti, i A DALT obre els genolls contra la banda. Baixa controlat.",
     "per": "Gluti major i mitjà alhora. Prepara el hip thrust i l'squat.",
     "yt": "glute bridge band abduction"},
    {"exercici": "Copenhagen plank (regressió: genoll)", "dosi": "2x20 s/costat",
     "què": "Plancha lateral amb la cama de dalt recolzada al banc.",
     "com": "De costat, colze a terra. Cama de DALT recolzada al banc pel tou de la cama (regressió) o pel peu (versió completa). Aixeca el maluc fins fer línia recta. Aguanta 20s.",
     "per": "Adductors — l'antagonista directe del TFL. Adductors forts = menys dominància del TFL = menys BIT.",
     "yt": "copenhagen plank adductor"},
]

PASSIVA = [
    {"posició": "Couch stretch", "temps": "120 s/costat",
     "com": "Genoll a terra a la base d'una paret, tíbia vertical contra la paret, cama davantera a 90°. Contreu el gluti del costat estirat i AMAGA EL CUL (retroversió pèlvica). Si la lumbar s'arqueja, allunya't de la paret.",
     "clau": "EL TEU #1. Si només fas un estirament a la vida, aquest. Flexor del maluc + recte femoral.",
     "yt": "couch stretch how to"},
    {"posició": "Pigeon pose (o figura-4 estirat)", "temps": "120 s/costat",
     "com": "Cama davantera flexionada davant teu (tíbia el més paral·lela possible al front), cama de darrere estirada. Baixa el tors sobre la cama davantera. Si el genoll molesta: figura-4 estirat al terra (turmell sobre el genoll contrari, estira cap al pit).",
     "clau": "Piriforme i gluti profund. Si el genoll et diu res, canvia a figura-4 sense pensar-ho.",
     "yt": "pigeon pose figure 4 stretch"},
    {"posició": "Estirament BIT modificat", "temps": "90 s/costat",
     "com": "De peu, creua la cama afectada DARRERE de l'altra. Inclina el tors cap al costat contrari, empenyent el maluc afectat cap enfora. Braç del costat afectat per sobre del cap.",
     "clau": "Posa la banda IT en tensió, no en fricció. És l'única manera segura de treballar-la.",
     "yt": "IT band stretch standing"},
    {"posició": "Papallona asseguda + inclinació", "temps": "90 s",
     "com": "Assegut, plantes dels peus juntes, talons a prop de l'engonal. Colzes sobre els genolls empenyent suau cap avall. Esquena LLARGA, inclina't des del maluc, no arrodonint l'esquena.",
     "clau": "Adductors. Complementa el Copenhagen.",
     "yt": "butterfly stretch adductors"},
    {"posició": "Isquios amb banda estirat", "temps": "90 s/costat",
     "com": "Estirat de panxa amunt, banda al peu. Puja la cama recta fins notar estirament. L'altra cama PLANA al terra (si s'aixeca, has anat massa). Lumbar enganxada al terra.",
     "clau": "Cadena posterior. Millor que tocar-te els peus de peu: no comprimeix la lumbar.",
     "yt": "supine hamstring stretch strap"},
    {"posició": "Postura del nen amb rotació", "temps": "60 s/costat",
     "com": "De genolls, cul als talons, braços estirats endavant. Passa un braç per SOTA del cos cap al costat contrari, deixant caure l'espatlla al terra.",
     "clau": "Dorsal i toràcica. El que et desfà les hores d'ordinador.",
     "yt": "childs pose thread the needle"},
    {"posició": "Respiració 90/90", "temps": "10 respiracions 4-7-8",
     "com": "Estirat de panxa amunt, cames sobre un banc o paret formant 90° al maluc i genoll. Inspira 4s pel nas, aguanta 7s, expira 8s per la boca. Respiració diafragmàtica: infla la panxa, no el pit.",
     "clau": "Baixa el to simpàtic. Impacte DIRECTE al Recovery del Whoop de l'endemà.",
     "yt": "90 90 breathing exercise"},
]

TORNADA_CALMA = [
    {"posició": "Couch stretch", "temps": "60 s/costat",
     "com": "Igual que a la rutina passiva, però més curt. Genoll a la paret, gluti contret, cul amagat.",
     "clau": "Els flexors acaben d'estar sota càrrega. Aquest és el millor moment del dia per estirar-los.",
     "yt": "couch stretch how to"},
    {"posició": "Pigeon o figura-4", "temps": "60 s/costat",
     "com": "El que et vagi millor. Si has fet squat pesat, figura-4 estirat és més amable amb el genoll.",
     "clau": "Gluti profund després de la càrrega.",
     "yt": "figure 4 stretch supine"},
    {"posició": "Estirament BIT modificat", "temps": "45 s/costat",
     "com": "De peu, cama afectada creuada darrere, inclinació lateral contrària.",
     "clau": "Obligatori els dies A i C (squat i unilateral). El teixit està calent: aprofita-ho.",
     "yt": "IT band stretch standing"},
    {"posició": "Dead hang a la barra", "temps": "30-45 s",
     "com": "Penjat de la barra, braços rectes, deixa anar el pes. Espatlles relaxades (no retretes).",
     "clau": "Descomprimeix la columna i l'espatlla. Sensacional després de dominades i press.",
     "yt": "dead hang benefits"},
    {"posició": "Respiració 4-7-8 asseguda", "temps": "8 respiracions",
     "com": "Assegut o estirat. Inspira 4s, aguanta 7s, expira 8s. Diafragmàtica.",
     "clau": "Talla la resposta simpàtica de la sessió. Et fa passar a mode recuperació ABANS de sortir del gym.",
     "yt": "4 7 8 breathing"},
]

MICRO = [
    {"quan": "Cada 90 min d'estudi/ordinador", "què": "30 s couch stretch/costat + 10 rotacions toràciques",
     "per": "Trenca l'escurçament del psoas per estar assegut. És el multiplicador real."},
    {"quan": "Post-bici (obligatori)", "què": "90 s couch stretch/costat",
     "per": "La bici és 2 hores de flexió de maluc mantinguda. Si no ho compenses, s'acumula."},
    {"quan": "Abans de dormir", "què": "60 s pigeon/costat",
     "per": "Gluti profund + baixa el to nerviós abans de dormir."},
]

FORCA_A = [
    {"patró": "Front Squat", "casa": "Goblet squat / Front squat amb manuelles", "apart": "Squat a barra guiada o premsa", "sr": "4 x 8-10", "tempo": "3-1-1-0",
     "què": "Squat amb la càrrega davant del pit.",
     "per": "Quàdriceps i core. La posició frontal força tors vertical i et protegeix la lumbar.",
     "com": "Peus amplada d'espatlles, puntes lleugerament obertes. Baixa controlat 3s, colzes alts, pit obert. Genolls segueixen la direcció dels peus. Fins on el maluc no es retrogiri.",
     "yt": "goblet squat technique"},
    {"patró": "Tracció vertical", "casa": "Dominades (llastrades si >10 reps)", "apart": "Poliada alta (pull-down)", "sr": "4 x 6-8", "tempo": "2-0-1-1",
     "què": "Estirar el cos cap amunt fins passar la barbeta.",
     "per": "Dorsal ample. És l'exercici que et dona l'esquena en V del físic híbrid.",
     "com": "Presa pronada una mica més ampla que espatlles. Comença retraient escàpules (baixa espatlles), no amb els braços. Puja fins que la barbeta passi la barra, baixa 2s controlat. No balancegis.",
     "yt": "pull up technique proper form"},
    {"patró": "Empenta horitzontal", "casa": "Press banca amb manuelles", "apart": "Press pectoral a màquina", "sr": "4 x 8-10", "tempo": "3-0-1-0",
     "què": "Empènyer la càrrega des del pit cap amunt.",
     "per": "Pectoral, tríceps, espatlla anterior.",
     "com": "Escàpules retretes i fixes al banc. Baixa 3s fins que les manuelles quedin a l'alçada del pit. Colzes a ~45° del cos, no oberts a 90°. Puja sense bloquejar del tot.",
     "yt": "dumbbell bench press form"},
    {"patró": "Accessori quàdriceps", "casa": "Bulgarian split squat", "apart": "Bulgarian split squat (peu al banc)", "sr": "3 x 10/cama", "tempo": "2-0-1-0",
     "què": "Squat a una cama amb el peu de darrere elevat al banc.",
     "per": "Quàdriceps + gluti unilateral. Corregeix desequilibris i és la teva eina quan les manuelles facin sostre.",
     "com": "Peu de darrere al banc, davanter a ~60-70 cm. Baixa vertical (no cap endavant), genoll de darrere gairebé a terra. Tot el pes al taló davanter. Tors lleugerament inclinat = més gluti.",
     "yt": "bulgarian split squat form"},
    {"patró": "Core anti-extensió", "casa": "Roda abdominal (des de genolls)", "apart": "Roda abdominal", "sr": "3 x 8-12", "tempo": "Controlat",
     "què": "Rodar cap endavant resistint que la lumbar s'arquegi.",
     "per": "Core dens de veritat. Molt superior als crunches per al teu objectiu.",
     "com": "Genolls a terra, retroversió pèlvica (cul amagat) ABANS de començar. Roda endavant només fins on puguis mantenir la lumbar plana. Si s'arqueja, has anat massa lluny.",
     "yt": "ab wheel rollout form"},
    {"patró": "Prevenció BIT", "casa": "Abducció de maluc de peu amb banda llarga", "apart": "Idem", "sr": "2 x 20/costat", "tempo": "Continu",
     "què": "Obrir la cama lateralment contra la banda.",
     "per": "Gluti mitjà. Gluti mitjà fort = menys fricció al BIT. És la teva assegurança.",
     "com": "Banda al turmell, ancorada baixa. Cama recta, obre lateralment sense inclinar el tors. Moviment petit i controlat: 30-40°, no més. Ha de cremar al lateral del maluc.",
     "yt": "standing hip abduction band"},
]

FORCA_B = [
    {"patró": "Hip Hinge", "casa": "Pes mort romanès amb manuelles", "apart": "RDL a barra guiada o poliada baixa", "sr": "4 x 8-10", "tempo": "3-1-1-0",
     "què": "Flexió de maluc amb cames gairebé rectes.",
     "per": "Isquios i gluti. És el patró que et falta si vius assegut.",
     "com": "Maluc enrere (com si toquessis una paret amb el cul), esquena plana SEMPRE. Manuelles llisquen per la cuixa. Baixa 3s fins notar estirament als isquios (~mitja tíbia). No és un squat: el genoll amb prou feines es doblega.",
     "yt": "romanian deadlift dumbbell form"},
    {"patró": "Empenta vertical", "casa": "Press militar assegut amb manuelles", "apart": "Press militar a màquina", "sr": "4 x 8-10", "tempo": "2-0-1-0",
     "què": "Empènyer la càrrega per sobre del cap.",
     "per": "Espatlla completa i estabilitat escapular.",
     "com": "Assegut amb esquena recolzada. Comença a l'alçada de les orelles. Puja fins gairebé bloquejar. NO arquegis la lumbar per compensar: si ho fas, et falta mobilitat toràcica (per això l'escalfament).",
     "yt": "seated dumbbell shoulder press form"},
    {"patró": "Tracció horitzontal", "casa": "Rem a una mà amb manuella (suport banc)", "apart": "Rem baix a poliada", "sr": "4 x 10", "tempo": "2-1-1-0",
     "què": "Estirar la càrrega cap al maluc.",
     "per": "Esquena mitjana i gruix. Compensa tot l'empenyer que fas.",
     "com": "Genoll i mà del mateix costat al banc, esquena paral·lela al terra i PLANA. Estira el colze cap enrere i amunt fins al maluc, no cap a l'espatlla. Pausa 1s a dalt. No rotis el tors.",
     "yt": "single arm dumbbell row form"},
    {"patró": "Cadena posterior", "casa": "Hip thrust amb manuella al maluc", "apart": "Hip thrust amb banda + suport", "sr": "3 x 12", "tempo": "2-2-1-0",
     "què": "Elevar el maluc des del terra amb l'esquena al banc.",
     "per": "Gluti major en el seu rang més fort. Potència de cama.",
     "com": "Escàpules al cantell del banc, peus plans. Puja fins que cuixa i tors formin línia recta. Pausa 2s dalt contraient gluti. Barbeta al pit — no miris al sostre ni arquegis lumbars.",
     "yt": "dumbbell hip thrust form"},
    {"patró": "Isquios", "casa": "Nòrdic curl excèntric o curl femoral amb banda", "apart": "Curl femoral a màquina", "sr": "3 x 6-8", "tempo": "4-0-1-0",
     "què": "Baixar el cos endavant resistint amb els isquios.",
     "per": "Isquios en excèntric. És el que et protegeix de tirades i complementa el RDL.",
     "com": "Genolls a terra, peus fixats (sota el banc o algú que et subjecti). Baixa el més lent possible (4s), cos recte com una taula. Quan no aguantis, cau a les mans. Puja ajudant-te amb els braços.",
     "yt": "nordic hamstring curl beginner"},
    {"patró": "Core anti-rotació", "casa": "Pallof press amb banda llarga", "apart": "Pallof press a poliada", "sr": "3 x 12/costat", "tempo": "2-2-2-0",
     "què": "Estendre els braços resistint que la banda et giri.",
     "per": "Core anti-rotació. El que et manté rígid al RDL i a la bici.",
     "com": "Banda ancorada al costat, a alçada del pit. De peu perpendicular. Mans al pit, estén els braços 2s, aguanta 2s, torna 2s. El tors NO ha de girar gens. Ha de cremar l'oblic.",
     "yt": "pallof press form"},
]

FORCA_C = [
    {"patró": "Unilateral quàdriceps", "casa": "Step-up al banc amb manuelles", "apart": "Step-up al banc", "sr": "4 x 10/cama", "tempo": "2-0-1-0",
     "què": "Pujar a un banc amb una cama.",
     "per": "Quàdriceps i gluti unilateral + estabilitat. Transferència directa a bici i senderisme.",
     "com": "Banc a alçada de genoll. Puja EMPENYENT amb el taló de la cama de dalt — no impulsis amb la de baix. Baixa 2s controlat. La cama de treball no baixa fins acabar les reps.",
     "yt": "dumbbell step up exercise form"},
    {"patró": "Unilateral hinge", "casa": "Pes mort a una cama amb manuella", "apart": "Idem amb poliada baixa", "sr": "3 x 10/cama", "tempo": "3-0-1-0",
     "què": "RDL a una cama.",
     "per": "Isquios, gluti i equilibri. Detecta i corregeix asimetries.",
     "com": "Manuella a la mà CONTRÀRIA a la cama de suport. Maluc enrere, cama lliure s'estén cap enrere en línia amb el tors. El maluc no s'ha d'obrir cap al costat. Baixa 3s.",
     "yt": "single leg romanian deadlift form"},
    {"patró": "Tracció vertical (variant)", "casa": "Dominades supinació (chin-up)", "apart": "Pull-down supinació", "sr": "3 x 8-10", "tempo": "2-0-1-1",
     "què": "Dominada amb presa invertida (palmells cap a tu).",
     "per": "Dorsal + bíceps. Més fàcil que la pronada: et deixa fer més reps i acumular volum.",
     "com": "Presa amplada d'espatlles, palmells cap a tu. Igual que la dominada: escàpules primer, barbeta sobre la barra, baixada de 2s.",
     "yt": "chin up proper form"},
    {"patró": "Empenta (variant)", "casa": "Press inclinat amb manuelles", "apart": "Press inclinat a màquina", "sr": "3 x 10", "tempo": "2-0-1-0",
     "què": "Press amb el banc inclinat 30-45°.",
     "per": "Pectoral superior i espatlla anterior. El que dona el pit 'ple' a dalt.",
     "com": "Inclinació 30-45° (més amunt = més espatlla, menys pit). Mateixa tècnica que el press pla: escàpules retretes, colzes a 45°.",
     "yt": "incline dumbbell press form"},
    {"patró": "Core dens (circuit)", "casa": "Hollow hold 30s → Dead bug 12/costat → Plancha lateral 30s/costat", "apart": "Idem", "sr": "3 voltes", "tempo": "—",
     "què": "Circuit de tres exercicis isomètrics i de control.",
     "per": "Core complet: anti-extensió, coordinació i lateral. Densitat sense impacte.",
     "com": "Hollow: lumbar SEMPRE enganxada al terra, braços i cames estirats. Dead bug: baixa braç i cama contraris sense que la lumbar s'aixequi. Plancha lateral: cos en línia, maluc alt.",
     "yt": "hollow hold dead bug side plank"},
    {"patró": "Condicional (sense impacte)", "casa": "Corda de saltar SI tolerància OK — si no: bici", "apart": "Idem", "sr": "6 x 45s / 15s off", "tempo": "—",
     "què": "Interval de condicional.",
     "per": "Capacitat aeròbica sense córrer.",
     "com": "⚠️ COMPTE BIT: saltar és flexió-extensió repetitiva. Comença amb 3 min TOTALS i observa. Si hi ha molèstia lateral, fora — passa a bici o remo.",
     "yt": "jump rope technique beginners"},
]

DIES = {
    0: {"nom": "Dilluns", "tipus": "forca", "titol": "FORÇA A", "sub": "Squat dominant",
        "exercicis": FORCA_A, "extra": "Escalfament complet (10 min) abans de començar."},
    1: {"nom": "Dimarts", "tipus": "passiva", "titol": "DESCANS · Mobilitat passiva", "sub": "18 min",
        "extra": "Al final del dia o post-activitat lleugera. Mai en fred: 3 min de bici o saltar suau abans."},
    2: {"nom": "Dimecres", "tipus": "forca", "titol": "FORÇA B", "sub": "Hinge dominant",
        "exercicis": FORCA_B, "extra": "Afegeix 30 s de dead hang a la barra abans de començar."},
    3: {"nom": "Dijous", "tipus": "micro", "titol": "DESCANS · Micro-dosi ampliada", "sub": "5 min",
        "extra": "Couch stretch 90 s/costat + Pigeon 90 s/costat."},
    4: {"nom": "Divendres", "tipus": "forca", "titol": "FORÇA C", "sub": "Mixt / unilateral / densitat",
        "exercicis": FORCA_C, "extra": "Escalfament complet (10 min) abans de començar."},
    5: {"nom": "Dissabte", "tipus": "micro", "titol": "ACTIVITAT · Bici / pàdel / natació", "sub": "Post-activitat: 5 min",
        "extra": "Post-activitat OBLIGATORI: couch stretch 90 s/costat + pigeon 60 s/costat."},
    6: {"nom": "Diumenge", "tipus": "passiva", "titol": "DESCANS · Mobilitat passiva", "sub": "18 min",
        "extra": "El bloc llarg de la setmana. Aprofita per fer l'escalivada i l'export de dades."},
}

DESCANSOS = [
    {"tipus": "Bàsics (squat, RDL, dominades, press)", "descans": "2-3 min"},
    {"tipus": "Accessoris (bulgarian, hip thrust, rem)", "descans": "90 s"},
    {"tipus": "Core / prevenció", "descans": "45-60 s"},
]
