# rutina.py — contingut estàtic del pla

FOAM = [
    {"zona": "TFL (2 dits sota la cresta ilíaca, davant-lateral)", "dosi": "60 s/costat", "nota": "Pressió sostinguda"},
    {"zona": "Gluti mitjà", "dosi": "45 s/costat", "nota": "Roller o pilota"},
    {"zona": "Vast lateral", "dosi": "45 s/costat", "nota": "Cadena lateral"},
]

DINAMIC = [
    {"exercici": "90/90 hip switch", "dosi": "10 canvis/costat", "nota": "Rotació de maluc"},
    {"exercici": "Couch stretch dinàmic", "dosi": "8 pulsacions/costat", "nota": "Gluti contret, no arquegis lumbars"},
    {"exercici": "World's greatest stretch", "dosi": "5/costat", "nota": "Amb rotació cap al sostre"},
    {"exercici": "Rotació toràcica quadrupèdia", "dosi": "8/costat", "nota": "Mà al clatell, obre el pit"},
    {"exercici": "Squat prying (goblet)", "dosi": "45 s", "nota": "Colzes empenyent genolls"},
    {"exercici": "Balanceig de cama frontal i lateral", "dosi": "12/direcció/cama", "nota": "Sense rebot"},
]

MINIBANDS = [
    {"exercici": "Monster walk lateral (banda 5 kg)", "dosi": "2x15 passos/direcció", "nota": "Gluti mitjà"},
    {"exercici": "Clamshell amb pausa 2s (banda 6 kg)", "dosi": "2x12/costat", "nota": "Rotadors externs"},
    {"exercici": "Pont de gluti amb abducció", "dosi": "2x15", "nota": "Gluti major + mitjà"},
    {"exercici": "Copenhagen plank (regressió: genoll)", "dosi": "2x20 s/costat", "nota": "Adductors"},
]

PASSIVA = [
    {"posició": "Couch stretch (genoll a la paret)", "temps": "120 s/costat", "clau": "EL TEU #1. Retroversió pèlvica, gluti contret"},
    {"posició": "Pigeon pose (o figura-4 estirat)", "temps": "120 s/costat", "clau": "Si el genoll molesta, figura-4 al terra"},
    {"posició": "Estirament BIT modificat (cama creuada + inclinació lateral)", "temps": "90 s/costat", "clau": "De peu, cama afectada darrere"},
    {"posició": "Papallona asseguda + inclinació", "temps": "90 s", "clau": "Colzes als genolls, esquena llarga"},
    {"posició": "Isquios amb banda estirat", "temps": "90 s/costat", "clau": "Cama recta, l'altra al terra"},
    {"posició": "Postura del nen amb rotació", "temps": "60 s/costat", "clau": "Braç per sota del cos"},
    {"posició": "Respiració 90/90 (cames sobre banc)", "temps": "10 respiracions 4-7-8", "clau": "Baixa el to simpàtic → Recovery"},
]

MICRO = [
    {"quan": "Cada 90 min d'estudi/ordinador", "què": "30 s couch stretch/costat + 10 rotacions toràciques"},
    {"quan": "Post-bici (obligatori)", "què": "90 s couch stretch/costat"},
    {"quan": "Abans de dormir", "què": "60 s pigeon/costat"},
]

FORCA_A = [
    {"patró": "Front Squat", "casa": "Goblet squat / Front squat amb manuelles", "apart": "Squat a barra guiada o premsa", "sr": "4 x 8-10", "tempo": "3-1-1-0",
     "què": "Squat amb la càrrega davant del pit.",
     "per": "Quàdriceps i core. La posició frontal força tors vertical i et protegeix la lumbar.",
     "com": "Peus amplada d'espatlles, puntes lleugerament obertes. Baixa controlat 3s, colzes alts, pit obert. Genolls segueixen la direcció dels peus. Fins on el maluc no es retrogiri.",
     "yt": "goblet squat technique"},
    {"patró": "Tracció vertical", "casa": "Dominades (llastrades si >10 reps)", "apart": "Poliada alta (pull-down)", "sr": "4 x 6-8", "tempo": "2-0-1-1",
     "què": "Estirar el cos cap amunt fins passar la barbeta.",
     "per": "Dorsal ample. És l'exercici que et dona l'esquena en V del físic híbrid.",
     "com": "Presa pronada una mica més ampla que espatlles. Comença retraient escàpules (baixa espatlles), no amb els braços. Puja fins que la barbeta passi la barra, baixa 2s controlat. No balancegis.",
     "yt": "pull up technique proper form"},
    {"patró": "Empenta horitzontal", "casa": "Press banca amb manuelles", "apart": "Press pectoral a màquina", "sr": "4 x 8-10", "tempo": "3-0-1-0",
     "què": "Empènyer la càrrega des del pit cap amunt.",
     "per": "Pectoral, tríceps, espatlla anterior.",
     "com": "Escàpules retretes i fixes al banc. Baixa 3s fins que les manuelles quedin a l'alçada del pit. Colzes a ~45° del cos, no oberts a 90°. Puja sense bloquejar del tot.",
     "yt": "dumbbell bench press form"},
    {"patró": "Accessori quàdriceps", "casa": "Bulgarian split squat", "apart": "Bulgarian split squat (peu al banc)", "sr": "3 x 10/cama", "tempo": "2-0-1-0",
     "què": "Squat a una cama amb el peu de darrere elevat al banc.",
     "per": "Quàdriceps + gluti unilateral. Corregeix desequilibris i és la teva eina quan les manuelles facin sostre.",
     "com": "Peu de darrere al banc, davanter a ~60-70 cm. Baixa vertical (no cap endavant), genoll de darrere gairebé a terra. Tot el pes al taló davanter. Tors lleugerament inclinat = més gluti.",
     "yt": "bulgarian split squat form"},
    {"patró": "Core anti-extensió", "casa": "Roda abdominal (des de genolls)", "apart": "Roda abdominal", "sr": "3 x 8-12", "tempo": "Controlat",
     "què": "Rodar cap endavant resistint que la lumbar s'arquegi.",
     "per": "Core dens de veritat. Molt superior als crunches per al teu objectiu.",
     "com": "Genolls a terra, retroversió pèlvica (cul amagat) ABANS de començar. Roda endavant només fins on puguis mantenir la lumbar plana. Si s'arqueja, has anat massa lluny.",
     "yt": "ab wheel rollout form"},
    {"patró": "Prevenció BIT", "casa": "Abducció de maluc de peu amb banda llarga", "apart": "Idem", "sr": "2 x 20/costat", "tempo": "Continu",
     "què": "Obrir la cama lateralment contra la banda.",
     "per": "Gluti mitjà. Gluti mitjà fort = menys fricció al BIT. És la teva assegurança.",
     "com": "Banda al turmell, ancorada baixa. Cama recta, obre lateralment sense inclinar el tors. Moviment petit i controlat: 30-40°, no més. Ha de cremar al lateral del maluc.",
     "yt": "standing hip abduction band"},
]

FORCA_B = [
    {"patró": "Hip Hinge", "casa": "Pes mort romanès amb manuelles", "apart": "RDL a barra guiada o poliada baixa", "sr": "4 x 8-10", "tempo": "3-1-1-0",
     "què": "Flexió de maluc amb cames gairebé rectes.",
     "per": "Isquios i gluti. És el patró que et falta si vius assegut.",
     "com": "Maluc enrere (com si toquessis una paret amb el cul), esquena plana SEMPRE. Manuelles llisquen per la cuixa. Baixa 3s fins notar estirament als isquios (~mitja tíbia). No és un squat: el genoll amb prou feines es doblega.",
     "yt": "romanian deadlift dumbbell form"},
    {"patró": "Empenta vertical", "casa": "Press militar assegut amb manuelles", "apart": "Press militar a màquina", "sr": "4 x 8-10", "tempo": "2-0-1-0",
     "què": "Empènyer la càrrega per sobre del cap.",
     "per": "Espatlla completa i estabilitat escapular.",
     "com": "Assegut amb esquena recolzada. Comença a l'alçada de les orelles. Puja fins gairebé bloquejar. NO arquegis la lumbar per compensar: si ho fas, et falta mobilitat toràcica (per això l'escalfament).",
     "yt": "seated dumbbell shoulder press form"},
    {"patró": "Tracció horitzontal", "casa": "Rem a una mà amb manuella (suport banc)", "apart": "Rem baix a poliada", "sr": "4 x 10", "tempo": "2-1-1-0",
     "què": "Estirar la càrrega cap al maluc.",
     "per": "Esquena mitjana i gruix. Compensa tot l'empenyer que fas.",
     "com": "Genoll i mà del mateix costat al banc, esquena paral·lela al terra i PLANA. Estira el colze cap enrere i amunt fins al maluc, no cap a l'espatlla. Pausa 1s a dalt. No rotis el tors.",
     "yt": "single arm dumbbell row form"},
    {"patró": "Cadena posterior", "casa": "Hip thrust amb manuella al maluc", "apart": "Hip thrust amb banda + suport", "sr": "3 x 12", "tempo": "2-2-1-0",
     "què": "Elevar el maluc des del terra amb l'esquena al banc.",
     "per": "Gluti major en el seu rang més fort. Potència de cama.",
     "com": "Escàpules al cantell del banc, peus plans. Puja fins que cuixa i tors formin línia recta. Pausa 2s dalt contraient gluti. Barbeta al pit — no miris al sostre ni arquegis lumbars.",
     "yt": "dumbbell hip thrust form"},
    {"patró": "Isquios", "casa": "Nòrdic curl excèntric o curl femoral amb banda", "apart": "Curl femoral a màquina", "sr": "3 x 6-8", "tempo": "4-0-1-0",
     "què": "Baixar el cos endavant resistint amb els isquios.",
     "per": "Isquios en excèntric. És el que et protegeix de tirades i complementa el RDL.",
     "com": "Genolls a terra, peus fixats (sota el banc o algú que et subjecti). Baixa el més lent possible (4s), cos recte com una taula. Quan no aguantis, cau a les mans. Puja ajudant-te amb els braços.",
     "yt": "nordic hamstring curl beginner"},
    {"patró": "Core anti-rotació", "casa": "Pallof press amb banda llarga", "apart": "Pallof press a poliada", "sr": "3 x 12/costat", "tempo": "2-2-2-0",
     "què": "Estendre els braços resistint que la banda et giri.",
     "per": "Core anti-rotació. El que et manté rígid al RDL i a la bici.",
     "com": "Banda ancorada al costat, a alçada del pit. De peu perpendicular. Mans al pit, estén els braços 2s, aguanta 2s, torna 2s. El tors NO ha de girar gens. Ha de cremar l'oblic.",
     "yt": "pallof press form"},
]

FORCA_C = [
    {"patró": "Unilateral quàdriceps", "casa": "Step-up al banc amb manuelles", "apart": "Step-up al banc", "sr": "4 x 10/cama", "tempo": "2-0-1-0",
     "què": "Pujar a un banc amb una cama.",
     "per": "Quàdriceps i gluti unilateral + estabilitat. Transferència directa a bici i senderisme.",
     "com": "Banc a alçada de genoll. Puja EMPENYENT amb el taló de la cama de dalt — no impulsis amb la de baix. Baixa 2s controlat. La cama de treball no baixa fins acabar les reps.",
     "yt": "dumbbell step up exercise form"},
    {"patró": "Unilateral hinge", "casa": "Pes mort a una cama amb manuella", "apart": "Idem amb poliada baixa", "sr": "3 x 10/cama", "tempo": "3-0-1-0",
     "què": "RDL a una cama.",
     "per": "Isquios, gluti i equilibri. Detecta i corregeix asimetries.",
     "com": "Manuella a la mà CONTRÀRIA a la cama de suport. Maluc enrere, cama lliure s'estén cap enrere en línia amb el tors. El maluc no s'ha d'obrir cap al costat. Baixa 3s.",
     "yt": "single leg romanian deadlift form"},
    {"patró": "Tracció vertical (variant)", "casa": "Dominades supinació (chin-up)", "apart": "Pull-down supinació", "sr": "3 x 8-10", "tempo": "2-0-1-1",
     "què": "Dominada amb presa invertida (palmells cap a tu).",
     "per": "Dorsal + bíceps. Més fàcil que la pronada: et deixa fer més reps i acumular volum.",
     "com": "Presa amplada d'espatlles, palmells cap a tu. Igual que la dominada: escàpules primer, barbeta sobre la barra, baixada de 2s.",
     "yt": "chin up proper form"},
    {"patró": "Empenta (variant)", "casa": "Press inclinat amb manuelles", "apart": "Press inclinat a màquina", "sr": "3 x 10", "tempo": "2-0-1-0",
     "què": "Press amb el banc inclinat 30-45°.",
     "per": "Pectoral superior i espatlla anterior. El que dona el pit 'ple' a dalt.",
     "com": "Inclinació 30-45° (més amunt = més espatlla, menys pit). Mateixa tècnica que el press pla: escàpules retretes, colzes a 45°.",
     "yt": "incline dumbbell press form"},
    {"patró": "Core dens (circuit)", "casa": "Hollow hold 30s → Dead bug 12/costat → Plancha lateral 30s/costat", "apart": "Idem", "sr": "3 voltes", "tempo": "—",
     "què": "Circuit de tres exercicis isomètrics i de control.",
     "per": "Core complet: anti-extensió, coordinació i lateral. Densitat sense impacte.",
     "com": "Hollow: lumbar SEMPRE enganxada al terra, braços i cames estirats. Dead bug: baixa braç i cama contraris sense que la lumbar s'aixequi. Plancha lateral: cos en línia, maluc alt.",
     "yt": "hollow hold dead bug side plank"},
    {"patró": "Condicional (sense impacte)", "casa": "Corda de saltar SI tolerància OK — si no: bici", "apart": "Idem", "sr": "6 x 45s / 15s off", "tempo": "—",
     "què": "Interval de condicional.",
     "per": "Capacitat aeròbica sense córrer.",
     "com": "⚠️ COMPTE BIT: saltar és flexió-extensió repetitiva. Comença amb 3 min TOTALS i observa. Si hi ha molèstia lateral, fora — passa a bici o remo.",
     "yt": "jump rope technique beginners"},
]

DIES = {
    0: {"nom": "Dilluns", "tipus": "forca", "titol": "FORÇA A", "sub": "Squat dominant",
        "exercicis": FORCA_A, "extra": "Escalfament complet (10 min) abans de començar."},
    1: {"nom": "Dimarts", "tipus": "passiva", "titol": "DESCANS · Mobilitat passiva", "sub": "18 min",
        "extra": "Al final del dia o post-activitat lleugera. Mai en fred: 3 min de bici o saltar suau abans."},
    2: {"nom": "Dimecres", "tipus": "forca", "titol": "FORÇA B", "sub": "Hinge dominant",
        "exercicis": FORCA_B, "extra": "Afegeix 30 s de dead hang a la barra abans de començar."},
    3: {"nom": "Dijous", "tipus": "micro", "titol": "DESCANS · Micro-dosi ampliada", "sub": "5 min",
        "extra": "Couch stretch 90 s/costat + Pigeon 90 s/costat."},
    4: {"nom": "Divendres", "tipus": "forca", "titol": "FORÇA C", "sub": "Mixt / unilateral / densitat",
        "exercicis": FORCA_C, "extra": "Escalfament complet (10 min) abans de començar."},
    5: {"nom": "Dissabte", "tipus": "micro", "titol": "ACTIVITAT · Bici / pàdel / natació", "sub": "Post-activitat: 5 min",
        "extra": "Post-activitat OBLIGATORI: couch stretch 90 s/costat + pigeon 60 s/costat."},
    6: {"nom": "Diumenge", "tipus": "passiva", "titol": "DESCANS · Mobilitat passiva", "sub": "18 min",
        "extra": "El bloc llarg de la setmana. Aprofita per fer l'escalivada i l'export de dades."},
}

DESCANSOS = [
    {"tipus": "Bàsics (squat, RDL, dominades, press)", "descans": "2-3 min"},
    {"tipus": "Accessoris (bulgarian, hip thrust, rem)", "descans": "90 s"},
    {"tipus": "Core / prevenció", "descans": "45-60 s"},
]
